apiVersion: v1
kind: Secret
metadata:
  name: school-ms-secret
  namespace: school-ms
type: Opaque
data:
  DB_USERNAME: bmFzaXI=
  DB_PASSWORD: bmFzaXI=
  MONGO_URI: bW9uZ29kYitzcnY6Ly9uYXNpcjpuYXNpckBzY2hvb2wudXlha3Fvei5tb25nb2RiLm5ldC8=
